### ISSUE TITLE
Using ngx-ui-scroll for pagination in an Ionic 4 app is not working properly

### ISSUE THREAD

**Issue by StriderRanger** [dhilt/ngx-ui-scroll#105]
Hello,

I am using ngx-ui-scroll to paginate a list of items following this logic:
- The new data of each page is appended to the end of the dataset, based on a subscription to the `lastVisible$` observable of the adapter.
- Each page contains a number of items that is calculated proportionally to the height of the screen devised by the average height of each item of the list.
- When calculating this number of elements per page, an offset is added so that the page contains more elements that exceeds the height of the viewport of the ui-scroll.

The problem that I am facing is that the pagination is not working in my ionic app until this offset is given a higher number (the value depends randomly  on the height of the viewport)

I created 2 examples, where one is made with angular and is working fine, and the other contains exactly the same code but in an Ionic 4 environment, and is not working as intended:
- The working [Angular example](https://stackblitz.com/edit/ngx-ui-scroll-pagination)
- The not working [Ionic example](https://stackblitz.com/edit/ngx-ui-scroll-ionic4-pagination), and it works once we increment the variable `pageItemsOffset ` to a higher number.

Thank you for your time!

**Comment by dhilt** [comment]
@StriderRanger  First, I see that Angular versions and ngx-ui-scroll are different in your 2 demos. Generally they need to be fixed... After I raised ngx-ui-scroll version up to the latest (1.2.0) in your first working demo, it became broken. Also, downgrading ngx-ui-scroll version to 1.1.2-rc.2  in you second not working demo makes it work.

So I think it's a matter of last package version, and I need time to investigate what might went wrong with last release. The change is [here](https://github.com/dhilt/ngx-ui-scroll/compare/2774ee19bdc61cf4ba2cabfc911f4a861938d14a...b1c90ac4914fbbbf00e91f0f94f55d852d9e03f4). Anyway, thanks for the issue! Let's hope it will be easy.

**Comment by StriderRanger** [comment]
Thank you for your reply and for clarifying the difference between the 2 packages :) 
I hope too that it will be easy, and while waiting for an official ui-scroll fix, I made [this warkaround](https://stackblitz.com/edit/ngx-ui-scroll-ionic4-pagination-warkaround):

I noticed that each time I couldn't scroll downward the `forward-padding-height`  has a `0` value. So I thought about changing the padding setting to the minimum value of 0.01, and it worked.

**Comment by dhilt** [comment]
@StriderRanger Finally I found the answer. The thing is you implemented your Datasource in a way it can't ensure synchronous data flow consistency. You set up only 5 items initially and then append more items by some process which is asynchronous and not synced with `Datasource.get` method implementation. But when the uiScroll receives some item list from your Datasource and its length is less than requested, he treats it as the end-of-file and stops asking for more items. 

Using `debug: true` (`devSettings`) you'll see following requests
- [0..3] --> resolved 4 items
- [-4..-1] --> resolved 0 items (begin-of-file is reached)
- [4..7] --> resolved 1 item, because your datasource has only 5 items initially (end-of-file is reached)
        
To make this more clear I just updated README:

> Datasource.get method must provide an array of count data-items started from index position. If there are no items within given range [index; index + count - 1], an empty array has to be passed. Empty result (or result which length is less than count) is being treated as the edge of the dataset (eof/bof), and no further requests for preceding/tailing items will be issued.

The solution is to move all the logic related to your dataset into the `Datasource.get` method implementation. You can request for new data items (say, loadMoreItems) exactly when `Datasource.get` wants them and defer the `success` callback execution until you receive your items. In other hand, if you want to have some preload mechanism, you still might request new items somewhere outside the `Datasource.get` in some random way, BUT your `Datasource.get` must know that the process of getting new items is running and must wait for its finishing to return uncut solid result. `[4..7]` request must be finished with 4 items. So you have to sync data requesting logic with `Datasource.get` implementation, while both requesting logic and `Datasource.get` might be asynchronous. 

Previous ngx-ui-scroll version had less strict (I would even say less safe) eof/bof checking logic. 1.2.0 version forces you to follow more explicit way of datasource implementation.

**Comment by StriderRanger** [comment]
Thank you for your insightful answer! So the problem was basically the asynchronous relationship between retrieving the data and how `Datasource.get` handles this data.

The main asynchronous treatment in my solution is the subscription to the `lastVisible$` observable, that is used to detect and trigger the call to the next page. There was no obvious way to sync this treatment with the `Datasource.get` implementation. I tried to create and subscribe to a `BehaviorSubject` that changes at the beginning and end of each load, and return the `success` method inside `Datasource.get` only when the loading is over and all the data is loaded, but it didn't work.

I ended up changing all the logic of how I paginate between the items, and I based my [new solution](https://stackblitz.com/edit/ngx-ui-scroll-ionic4-pagination-workaround3) on the [Async Pages Datasource](https://dhilt.github.io/ngx-ui-scroll/#/datasource#pages). My main objective is to have a uiScroll that is at the same time quick and that doesn't consume a lot of resources:
1.  I have to generate the data only once (which is similar to loading data from a local database), and this is imitated by invoking the method `generateItems` in my example
2. When the data is generated, it is loaded in the `data` variable
3. If the data is already loaded I just have to read it from the `data` variable without loading it again.

All seems to work fine :)
