### ISSUE TITLE
adapter.reload doesn't update the view

### ISSUE THREAD

**Issue by lmreicks** [dhilt/ngx-ui-scroll#120]
Because I have data that changes based on filters, I'm using adapter.reload() to reload the view when filters change. Sometimes, the reload doesn't actually reload the view. I'm not sure if this is a bug, or if there is a better way to accomplish what I'm trying to do.

I forked the repo and I've been trying to track some of this stuff down and it looks like it doesn't detect changes unless 'doClip' is true? Could you explain what this means, or if there's a way to override this?

```javascript
// need to apply Buffer.items changes if clip
 if (scroller.state.clip.doClip) {
  scroller.runChangeDetector();
}
```

**Comment by dhilt** [comment]
@lmreicks Thanks again! If you forked the repo, may I ask you to look at PR https://github.com/dhilt/ngx-ui-scroll/pull/117 branch (bug-112_error-while-trying-to-invoke-reload-method) and try it in your environment? That PR massively improves the reload process implementation. And it is going to be released soon, so another look could be very useful (and it might solve your issue).

Having `OnPush` strategy

https://github.com/dhilt/ngx-ui-scroll/blob/b54e390a82b652dd25d9f49d17c7646be5a7c49b/src/ui-scroll.component.ts#L15

the ui-scroll component has to make data-bidings explicitly. And that particular case you mentioned above is dedicated to tell the ui-scroll component that some items had been removed from the buffer and the Angular must rebuild the DOM based on changed items data array. I believe it's not the case we need to look at.

I think that in your App the reload might work improperly due to bad asynchronicity handling, which should be improved in the PR https://github.com/dhilt/ngx-ui-scroll/pull/117. But if not, I'd like to see the console log that you can turn on, copy to a file and attach to your next reply

```
datasource: {
  get: /*...*/,
  devSettings: {
    debug: true;
    logProcessRun: true;
  }
}
```

Also, the best option would be to provide a stand-alone repro, for it will significantly increase the chance of quick fix. You may fork [this stackblitz demo](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-3-0).

**Comment by dhilt** [comment]
Since ngx-ui-scroll v1.4.1, the scroller workflow is not responsible for triggering the Change detector. Now the only place where it might happen is the UiScrollComponent:

https://github.com/dhilt/ngx-ui-scroll/blob/225bfdcc21c6c1086cdef83f0263a205802b5c69/src/ui-scroll.component.ts#L61

Marking the view as changed happens in response to any `items` array changes during common workflow processes (fetch, clip) and adapter processes (reload, append, prepend, remove).

If there are any problems with change detection, please, feel free to create a new issue.
