### ISSUE TITLE
Adapter.reload fails if pass null instead of undefined

### ISSUE THREAD

**Issue by DaveLomber** [dhilt/ngx-ui-scroll#126]
Hi there

I just realized if call `Adapter.reload(undefined)` then it works, but if call `Adapter.reload(null)` then it fails  

After src code checking I found the following:

```
    if (typeof startIndex !== 'undefined') {
        this.startIndex = startIndex;
    }
```

My suggestion is to replace it to :

```
    if (startIndex) {
        this.startIndex = startIndex;
    }
```

So it will work with null as well

**Comment by dhilt** [comment]
@DaveLomber  The signature of the `Adapter.reload` method is fixed in the Readme

<img width="317" alt="Screenshot 2020-01-23 at 18 16 04" src="https://user-images.githubusercontent.com/4365660/72996850-70ba2b00-3e0c-11ea-9aa0-b99f8be7d9ba.png">

So `null` can't be fine for `startIndex?: number`, you'll just get TypeScript error

>  TS2345: Argument of type 'null' is not assignable to parameter of type 'number | undefined'.

The `typeof startIndex !== 'undefined'` check is added for ones who won't use TS.

**Comment by dhilt** [comment]
Since ngx-ui-scroll v1.6.1, the validation of the Adapter methods arguments had become more strict and unified:

https://github.com/dhilt/ngx-ui-scroll/blob/1abb97d0d15a59f22da2399520b6c029c6069a09/src/component/inputs/adapter.ts#L33-L37

INTEGER allows only numbers or non-empty strings

https://github.com/dhilt/ngx-ui-scroll/blob/1abb97d0d15a59f22da2399520b6c029c6069a09/src/component/inputs/validation.ts#L11-L14

and the result must pass through the checking on the equality with the result of `parseInt` call:

https://github.com/dhilt/ngx-ui-scroll/blob/1abb97d0d15a59f22da2399520b6c029c6069a09/src/component/inputs/validation.ts#L27-L31

At the TypeScript level it is still `number` or `undefined` as it fixed in the Readme.
