### ISSUE TITLE
Detect first load of the ui-scroll

### ISSUE THREAD

**Issue by StriderRanger** [dhilt/ngx-ui-scroll#143]
Hello,

I have a case where the items of the ui-scroll change their height asynchronously, and I need to scroll to the bottom of the list once the check of the first load is over, and before the user performs a manual scroll.
I thought about using a counter to base my check on the number of times we call the `Adapter.get` method, but The first load calls the `Adapter.get` method sometimes once and sometimes twice (Maybe it depends on the number of the elements that are loaded in the DOM at the first time), and using a counter wasn't a reliable method.

If a sample or more information is needed to make things more clear please let me know.

Thanks!

**Comment by dhilt** [comment]
@StriderRanger One or more `get` calls could be handled via self-destructing `isLoading$` subscription in case that calls occur in the same workflow cycle:

```js
adapter.isLoading$.pipe(
  filter(isLoading => !isLoading),
  take(1)
).subscribe(() => {
  // ... autoscroll
})
```

This should be run after `check` process is done, because `check` process spends 1 separate workflow cycle. I have a thought to join `check` wf cycle with the following `get` wf cycles (if they are present) into a single wf cycle, but for now (v1.4.1) we have 2 cycles, which means 2 `isLoading` switches, which forces to make the subscription (see above) after the first wf cycle is done and before the second one is started. Applying to the App code, this subscription could be made

  1) **inside `get` body**, when you know the `check` is running; 
  2) **right after `check` call**, wrapped in another `isLoading$` subscription which should allow to skip the first (check-related) wf cycle.

I just realized, that the second option could be done with rxjs skip operator, so the result suggestion is to use use following synchronously after the `Adapter.check` call:

```js
adapter.check();
adapter.isLoading$.pipe(
  filter(isLoading => !isLoading),
  skip(1),
  take(1)
).subscribe(() => {
  // ... autoscroll
})
```

This might be changed in the future! `skip(1)` will be unnecessary if I provide cycles merging on the scroller end.

Sorry for all these reflections, I want you to know the way I'm thinking on the issue as it might be useful. 

Also, what are you planning to do if the user scrolls before `check`-related `get` calls are done? In this case the autoscroll will be in conflict with the user scroll...

**Comment by StriderRanger** [comment]
@dhilt Thank you for your constant help :) It was insightful to know how the `get` and the `check` methods interact regarding their wf cycles.
I used the `Adapter.isLoading$` observable but I didn't get the wished result. Perhaps because I need to scroll to bottom on manual check, when all actual items of the ui-scroll take their final size.

I tried another approach that seems to work , and If understand things right, it bypass at the same time the case when the user scrolls before `check`-related `get`: Since I am in a mobile context, I detected the user scroll using the `touchmove` event:
```
addScrollListener() {
    let _self = this;
    document.addEventListener('touchmove', function _listener() {
      console.log("scrolled...")
      _self.userScrolled = true;
      document.removeEventListener("touchmove", _listener, true);
    }, true);
  }
```
This way, after each manual `Adapter.check()` call, I test the value of the  `userScrolled ` variable, and I scroll to bottom only when it's still `false`.

If you think that it will be more beneficial to push further the `Adapter.isLoading$` approach that you showed me, I can create a sample to be able to run some tests. Otherwise, the `touchmove` approach is working for now, but to make it more general, other events must be taken into account, like mouse-scroll-related and keyboard-scroll-related events.

**Comment by dhilt** [comment]
@StriderRanger Unfortunately, there is no way to get the difference between the user scroll event and the artificial one. Remembering the position before artificial scroll, setting the flags and other tricks don't cover all possible cases. [Just saw [your edit on SO](https://stackoverflow.com/a/31688482/3211932)] But for the mobile context, I think, this is appropriate way.

Also, I would consider an option to allow autoscroll only if the `check` should be run when the scroller is silent (`isLoading` is false). I know, if the `check` will cause `datasource.get` method to run, it may take time enough for the user can start scrolling, and we'll fall into the conflict. But this way we'll prevent the conflict in case the user started scrolling before the `check`. Never mind...

**Comment by StriderRanger** [comment]
@dhilt I understand that it's essential to assure that the scroller is not loading (`Adapter.isLoading = false`) before to perform an operation like scrolling in the list. This way some unintended behaviors could be avoided.
As for detecting the user scroll I couldn't find neither a proper way to predict all the possible cases, this is why I sticked only to the `touchmove` event since I am in a mobile context.
Can we consider that this issue is solved, or should it be kept opened to see if there is other possibilities?

**Comment by dhilt** [comment]
I think we are done, thank you for the discussion and please open new issues at any time!
