### ISSUE TITLE
Sometimes 'adapter.isLoading' can be true inside 'adapter.relax' callback

### ISSUE THREAD

**Issue by DaveLomber** [dhilt/ngx-ui-scroll#187]
Hi everyone, 

I have noticed one interesting thing

Let's say I have a method to append an item to adapter:

```
private doAdapterAppend(item, eof = false) {
  this.datasource.adapter.relax(() => {
    console.log("isLoading=", this.datasource.adapter.isLoading);    

    this.datasource.adapter.append([item], eof).then(res => {
     console.log("res", res);
   });
  });
}
```

And now let's say I call this method 2 times pretty quickly (e.g. another user sent me 2 messages very quickly so I want to add them all into adapter)

With this use case, for a 2nd method call I can get an 'isLoading=true' log, which means it's not safe here to call 'append'

To address this issue I did like this:

```
private doAdapterAppend(item, eof = false) {
  this.datasource.adapter.relax(() => {
    console.log("isLoading=", this.datasource.adapter.isLoading);    

    if (this.datasource.adapter.isLoading) {
      this.doAdapterAppend(item, eof); // loop
      return;
    }

    this.datasource.adapter.append([item], eof).then(res => {
     console.log("res", res);
   });
  });
}
```

so it's more or less works well 

I just want to clarify is it a right way to do it and is there any better way ?

Thank you I advance

**Comment by DaveLomber** [comment]
Btw, 
the same was before 'relax' API available - with 'isLoading$', 
so it's more a general thing, not related to 'relax' API itself

**Comment by dhilt** [comment]
@DaveLomber  I see... Current implementation does not allow to run Adapter methods many times synchronously, it means we need to build an explicit sequence of promises:

```js
await adapter.relax()
adapter.append(args1)
await adapter.relax()
adapter.append(args2)
// etc
```

or

```js
await adapter.relax()
await adapter.append(args1)
await adapter.append(args2)
// etc
```

I would agree that this requirement seems annoying if the Adapter calls (like append) can appear randomly, for example, in response to new items coming via sockets. The App should have a kind of event bus to handle such income, to make it sequential for the Adapter.

You suggested a recursive loop, I think it is not the best approach. Instead, I would accumulate Adapter calls in live array and check if it is not empty when current Adapter call is done.

**Comment by dhilt** [comment]
But I also think that the desired behaviour can be achieved by updating the body of `Adapter.relax` method. Let's take a look

https://github.com/dhilt/ngx-ui-scroll/blob/92845ef057f0d99fbb9ee0a2d7246ed7f8262ba2/src/component/classes/adapter.ts#L314-L331

Using the callback signature of `Adapter.relax` method allows to handle two concurrent Adapter calls, because the first one is invoked immediately (L317) if the Scroller truly relaxes (L315), and has get the UIScroll Workflow started after the first append is run. So the second call falls into awaiting and produces a promise (L321). Other sequential calls (third+) will pass the Promise way and _they all will be triggered at once_, when the first call finishes (L323). That's the problem.

What if we combine `isLoading$` and `relax$` on line 323? And resolve the promise (or invoke the callback) only when both observables deliver the Workflow **and** the Adapter relaxation? The `relax$` observable fires `false` immediately after the Adapter method is called, so the "next" call will wait for the "previous" one.

```ts
combineLatest(this.isLoading$, this.relax$)
  .pipe(
    filter(([isLoading, relax]) => !isLoading && !!relax),
    take(1)
  )
  .subscribe(() => {
    if (typeof callback === 'function') {
      callback();
    }
    resolve();
  })
```

This needs to be investigated and perhaps such improvement would allow to solve the issue on the lib end. Anyway, this is important case, thank you for raising it!

**Comment by DaveLomber** [comment]
Hi @dhilt 
appologze for not getting back with my feedback 

Your proposal sounds good and I think we should try it, 

otherwise, my app has lots of places like this:

```
private doAdapterAppend(item, eof = false) {
  this.datasource.adapter.relax(() => {
    console.log("isLoading=", this.datasource.adapter.isLoading);    

    if (this.datasource.adapter.isLoading) {
      this.doAdapterAppend(item, eof); // loop
      return;
    }

    this.datasource.adapter.append([item], eof).then(res => {
     console.log("res", res);
   });
  });
} 
```

which is a bit annoying... 


I'm happy to be a beta tester of this feature 👍

**Comment by dhilt** [comment]
@DaveLomber I opened issue #220, it relates to the problem that we discussed here. The fix I suggested above will not work,  the situation is more complex, and I'm not sure if it could be easily done on the lib' end. But anyway, with #220 we are getting closer to the problem' core.
