### ISSUE TITLE
Scroll to items which are not loaded into DOM

### ISSUE THREAD

**Issue by Disane87** [dhilt/ngx-ui-scroll#189]
Hey @dhilt thank you for this awesome project!
After an evening having fun with this, i really love it and have already a really handy feature request:

Actually I use this scolling for a chat app and now I want to scroll programatically to specific items (like when somebody searches a really old message text). Could this be possible?

But imho there are some open questions:
1) If I have a list with 1000 items and only showing the last 100. When found an item e.g. the 60th (in my chat app) should the `scrollToItem` load all the items between the last rendered one and the item to scroll by or only the "chunk" in which the items resides?
2) If yes, would this behavior be against the virtual scrolling concept?

**Comment by dhilt** [comment]
@Disane87  Thanks for your feedback and the issue!

First, I think that the Scroller can't fetch and render all items between current and wanted indexes, because there may be thousands and more items in a range and I don't want the UiScroll to be responsible for potential hangings. I will suggest the App based solution below, but first I want to think, is it possible to solve the issue on the lib end in another way.

 - Basically, the problem could be accurately solved in case of constant heights of messages: we know current index (Y), we know wanted index (X), we know item height (H), so the end position is just something like `Y - X * H`.

 - If there are random heights but we already had all messages from Y to H during current session, then the procedure can be updated to continue work precisely by using internal UiScroll Cache: `Y - [Y..H].reduce(getCahcedItemHeight)`.

 - But if there are random heights and we don't know what height does every [Y..H] item have, then precise solution becomes impossible. Sure, `getCahcedItemHeight` deals with unknown items and provides average value for the indexes that had never been rendered, but it can not be used for such purpose. The result will be inaccurate. User might even not see his message after such "scroll".

Chat means random heights and nearly unlimited number of items. No, this can't be done precisely in a single run. Let's take a look on what can be done on the App's end.

1. If you see that the desired index is out of current Buffer range, then you may start scrolling up until the Buffer got the index you want to show. For example, if you didn't specify min index and scrollbar parameters don't show anything out of current Buffer (no virtual items), then `scrollTop = 0` is the way to go:

```ts
  const scrollToIndex = (INDEX) {
    let found = false;
    adapter.fix({ updater: ({ $index }) => found = found || $index === INDEX});
    if (found) { // or if (viewportElement.querySelector(`[data-sid="${INDEX}"]`))
      return;
    }
    adapter.fix({ scrollPosition: 0 }); // or viewportElement.scrollTop = 0
    adapter.isLoading$
      .pipe(filter(v => !v), take(1))
      .subscribe(() => scrollToIndex(INDEX));
  };

  scrollToIndex(-999);
```

This is very basic algorithm, it does not take into account following cases:

 - wanted index is lower than current one (need to scroll down)
 - there are virtual items affecting the viewport scrollbar params (it won't be easy, but is possible)
 - user might want to interrupt the process

2. Instead of all that tricks, perhaps you want just to reload the viewport to specific index:

```
  this.datasource.adapter.reload(-999);
```

**Comment by Disane87** [comment]
Thank you for your detailed reply :-) need to dig into this and discovers a way how I can achieve this with your advices. Thank you very much!
