### ISSUE TITLE
Incorrect behavior when scroll up

### ISSUE THREAD

**Issue by FirstVertex** [dhilt/ngx-ui-scroll#193]
You can see in demo here
https://dhilt.github.io/ngx-ui-scroll/#/datasource#unlimited-bidirectional

When you try to scroll up, thumb goes way up and is not under the mouse.

I think this lib has problems with scroll up.  All demos seem broken when scroll up.  It gives incorrect UX when scroll thumb goes up away from mouse.

**Comment by dhilt** [comment]
@hughanderson4 Could you specify what behaviour you are expecting and what is the difference with the existing one? For me scroll-up looks fine and it works the same way as in all 55 prior versions of the lib. I really have no idea what might be wrong, so it would be nice if you also could attach visual sample (gif, video).

Also, I admit you may face some device specific issue, in that case I would ask you to provide appropriate information: device, OS and browser versions. 

And the last thing, maybe you are experiencing unlimited-top-border case as unusual due to all these back jumps and scrollbar size changes... Maybe [limited sample](https://stackblitz.com/edit/ngx-ui-scroll-1-7-0-limited?file=src/app/app.component.ts) will look more anticipated for you.

**Comment by dhilt** [comment]
I believe this issue relates to issue [210 (Scroll thumb jumps away from mouse cursor when scrolling up, Win 10](https://github.com/dhilt/ngx-ui-scroll/issues/210)), which had beed fixed in ngx-ui-scroll v1.8.2.
