### ISSUE TITLE
Scroll on nth element 

### ISSUE THREAD

**Issue by aammfe** [dhilt/ngx-ui-scroll#194]
Hello!!
Great package 
I would like to know how we can scroll on nth element ?
There [startIndex](https://dhilt.github.io/ngx-ui-scroll/#/settings#start-index) property but I'm looking for specific function like scrollToIndex | ScrollTo(predicate)  (both would be awesome) 
if there is please provide example for it as well 
Thanx

**Comment by dhilt** [comment]
@aammfe If the item you want to scroll in does exist in current Scroller buffer, you may find it and scroll into it manually. Otherwise, I would `reload`:

```ts
scrollToIndex(index: number) {
  const viewport: HTMLElement = document.querySelector('.viewport'); // use native ref instead
  let found: HTMLElement | null = null;
  this.datasource.adapter.fix({
    updater: ({ $index, element, data }) =>
      !found && $index === index ? found = element : null
  });
  if (found && viewport) {
    this.datasource.adapter.fix({
      scrollPosition: found.offsetTop - viewport.offsetTop // not sure if this calculation is 100% fine
    });
  } else {
    this.datasource.adapter.reload(index);
  }
}
```

Instead of using [adapter-fix-updater](https://dhilt.github.io/ngx-ui-scroll/#/experimental#adapter-fix-updater) technique, you may try to find appropriate element by `viewport.querySelector('[data-sid="999"]')`, but "updater" is more flexible as it has access to items data. Also, I would recommend to protect `scrollToIndex` call by `relax` method:

```ts
 await this.datasource.adapter.relax();
 this.scrollToIndex(999);
```

or 

```ts
this.datasource.adapter.relax(() =>  this.scrollToIndex(999));
```

With `reload` you are loosing min and max indexes that were achieved during previous session, it resets the viewport scrollbar params. This issue can be avoided by setting min/maxIndex settings on Datasource initialization, if you know the boundaries and they are fixed. Otherwise, you may try to use [reset](https://dhilt.github.io/ngx-ui-scroll/#/adapter#reset) instead of `reload` and re-fix min/max indexes at the settings level:

```ts
this.datasource.adapter.reset({
  settings: {
    startIndex: index_to_scroll,
    minIndex: previous_min_index,
    maxIndex: previous_max_index,
  }
});
```

These are the basic ideas that can be applied when we need to scroll programmatically. I would be glad to continue this discussion. Maybe we will come to new API or standardise this technique at the App level. Also, there is one parallel thread that relates to this one (https://github.com/dhilt/ngx-ui-scroll/issues/189), it also may contain something useful.

**Comment by aammfe** [comment]
Thanx !!
