### ISSUE TITLE
Support ancestor (instead of parent) viewport

### ISSUE THREAD

**Issue by ChaseOxide** [dhilt/ngx-ui-scroll#195]
Current implementation enforces (or at least based on what I've tried) a html structure like

```html
<div class="viewport">
  <div *uiScroll="let item of datasource">
    <b>{{item.text}}</b>
  </div>
</div>
```

Is is possible to support a structure that wraps *uiScroll with another layer of html element? e.g.

```html
<!-- overflow: scroll on viewport -->
<div class="viewport">
  <div>
    <div *uiScroll="let item of datasource">
      <b>{{item.text}}</b>
    </div>
  </div>
</div>
```

**Comment by dhilt** [comment]
@ChaseOxide Currently no, but it might be nice option. What about the following syntax?

```html
<div ui-scroll-viewport class="viewport">
  <div>
    <div *uiScroll="let item of datasource">
      <b>{{item.text}}</b>
    </div>
  </div>
</div>
```

We'll need to associate new viewport in some way, and `element.closest('[ui-scroll-viewport]')` seems the most simple approach. With this feature there will be 3 options for the viewport:

 - `*uiScroll` nearest parent if there is no "ui-scroll-viewport" element in the tree and `settings.window` is not set to true;
 - "ui-scroll-viewport" element if present and `settings.window` is not set to true;
 - `document` if `settings.window` is set to true, no matter of "ui-scroll-viewport";

**Comment by ChaseOxide** [comment]
@dhilt That syntax looks great, but I think it may not work well under certain conditions

- Viewport is on a different component (probably not easy to search for the directive)
- Doesn't allow host component to be the viewport
- Viewport is on a parent component, which we cannot modify the original code (e.g. generated by third-party library)

**Comment by dhilt** [comment]
@ChaseOxide Well, that makes sense. Another thing comes to mind, it will drastically increase flexibility but might seem dangerous:

```js
datasource = new Datasource({
  get,
  settings: {
    viewport: 'article > div' // just qury-selector string 
  }
});
```

And then instead of

https://github.com/dhilt/ngx-ui-scroll/blob/92845ef057f0d99fbb9ee0a2d7246ed7f8262ba2/src/component/classes/viewport.ts#L38-L39

in non-entire window case there will be something like

```js
this.scrollEventElement = null;
if (settings.viewport) {
  try {
    this.scrollEventElement = this.element.closest(settings.viewport);
  } catch(e) {
    console.warn('bad viewport selector, will take closest parent');
  }
}
if (!this.scrollEventElement) {
  this.scrollEventElement = this.element.parentElement as HTMLElement; 
}
this.hostElement = this.scrollEventElement; 
```

This approach includes the previous one and covers all possible scenarios of DOM tree traversing, but it puts an additional responsibility on the lib user. For example, we constructed appropriate selector for passing through some 3-party component, then it released an update and its html is changed... Is it an acceptable price for such flexibility?..

**Comment by ChaseOxide** [comment]
@dhilt or another alternative is to make `viewport` accept `HTMLElement` type

The usage will be as follows:

1. Viewport within the same component - Make use of [ViewChild](https://angular.io/api/core/ViewChild)

```html
<div class="viewport" #viewport>
  <div>
    <div *uiScroll="let item of datasource"></div>
  </div>
</div>
```

```ts
@Component()
class MyComp {
  @ViewChild('viewport', { static: true }) viewportRef: ElementRef<HTMLElement>;
  datasource = new Datasource({
    get,
    settings: {
      viewport: this.viewportRef.nativeElement
    }
  });
}
```

2. Viewport as host element - Inject [ElementRef](https://angular.io/api/core/ElementRef)

```html
<div>
  <div *uiScroll="let item of datasource"></div>
</div>
```

```ts
@Component()
class ViewportComp {
  datasource = new Datasource({
    get,
    settings: {
      viewport: this.elementRef.nativeElement
    }
  });

  constructor(private elementRef: ElementRef<HTMLElement>) {}
}
```

3. Nested components (`*uiScroll` is on a different component) - Make use of option 1 or 2 with Angular Service or [Input](https://angular.io/api/core/Input) to pass the reference

4. Viewport source cannot be modified, and has no way to direct reference element - Make use of [Document.querySelector](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) or [Document.getElementById](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById)

```ts
@Component()
class MyComp {
  datasource = new Datasource({
    get,
    settings: {
      viewport: this.document.getElementById('viewport')
    }
  });

  constructor(@Inject(DOCUMENT) private document: Document) {}
}
```

Personally, I think `viewport` should not accept `string` type, and user should query the element themselves (as suggested in 4). Also, by passing the query responsibility to the user, the lib wouldn't need to do the hack-ish if statements (or try/catch).

Another small suggestion I have is to combine this property with `windowViewport`, otherwise the lib has to specify in the docs which settings takes precedence

**Comment by dhilt** [comment]
@ChaseOxide Great! I think passing the HTML element would be the best option. It will still require checking/validation but it could be done at the Settings class layer where the other settings are being checked. The `windowViewport` setting should exist explicitly a) because the lib acts differently in the entire-window case (some code is different), b) due to the purpose of backward compatibility. Also, I think the user should not be obliged to pass the only possible "viewport" entity in the entire-window case because the lib won't be able to detect the problem if he fails. So yes, let the doc specify a priority: window -> viewport -> nothing.

**Comment by ChaseOxide** [comment]
Sounds good to me

**Comment by dhilt** [comment]
Closing this per ngx-ui-scroll v1.8.1 is on npm, the release contains the API we discussed in this issue.
Details are in demo doc: https://dhilt.github.io/ngx-ui-scroll/#/experimental#viewportElement-setting.
