### ISSUE TITLE
Scroll jumping on iOS

### ISSUE THREAD

**Issue by ChaseOxide** [dhilt/ngx-ui-scroll#197]
Similar to #87, this can still happen when scrollbar resizes.

To reproduce:

1. Scroll to the edge of scrollbar
2. Keep finger touched on screen (to tell the device keep the viewport on same position)
3. Notice previously rendered items have a very different position (usually offscreen) after scrollbar resizes

I believe it's caused by scroll having an incorrect position after scrollbar resizes, it doesn't happen after the scrollbar stops resizing

Tested on ngx-ui-scroll v1.7.0, Safari on iOS 13.4.1

**Comment by dhilt** [comment]
@ChaseOxide I didn't work with Safari much, do you mean the following difference?

|Chrome|Safari|
|:--|:----|
| ![Jul-19-2020 03-19-07](https://user-images.githubusercontent.com/4365660/87864262-cf510380-c96e-11ea-93dd-65c5926d3400.gif) | ![Jul-19-2020 03-20-06](https://user-images.githubusercontent.com/4365660/87864261-ca8c4f80-c96e-11ea-8235-0a23caf6a01b.gif) |

Resizing happens when the lib loads/renders new rows that had never been rendered before and min/max indexes are not set. After new rows are rendered at the top of the viewport, the lib makes single back-jump to show us exactly the same view as we had before new rows loading. Basically this works properly on Safari as I can see from the keyboard experience. But looks like it goes differently when an inertia device is in game. The nature of such behaviour seems mysterious. Maybe inertia scroll events have a kind of magical priority over synthetic back-jump events in Safari case, despite the `requestAnimationFrame` synchronization technique which was applied in ngx-ui-scroll v1.6.0 when the issue #87 was closed... 

It needs to be investigated and I will not be able to do it quick, I'm afraid. So I would appreciate any help.

**Comment by ateto** [comment]
I faced this issue and the solution I found was to change the style of the scroll container div dynamically just before calling the "success" callback. I changed the value of 'overflow-y' to 'hidden'. Then after the callback, I revert it back to 'auto' using setTimeout for 10 milliseconds. This works fine on iPad running iOS 13.

This solution removes the scroll feature from the container. Hence it forces the browser to disable the scroll actions before adding the data. This breaks the crazy jumbing on iOS.

**Comment by dhilt** [comment]
@ateto I wonder if this approach affects non iOS environments... Can you make a demo? you may fork [this stackblitz](https://stackblitz.com/edit/ngx-ui-scroll-1-11-0-angular-11). This may be very helpful for the community. Also, if the approach has no side effects (or side effects can be minimized), it would be possible to add dev-setting to enable the feature on the lib's end.

**Comment by ateto** [comment]
Sure. Below is a demonstration. 
https://stackblitz.com/edit/angular-ivy-sp4fjp

In my use-case, I assumed data will be fetched in the first time from the server on chunks (Therefore, there will be a network delay.). Then it will be cached and subsequent reads will be served from the cache.

I tested it also on Firefox 83 (mac OS version), chrome 87 (mac OS version), Safari 12 (mac OS ), Chrome 86 (android version), Firefox 83 (android version).

It works very well on all of them. The only side effect I found was only in case of Safari 12 (mac OS) where although the scroll works well, there is a noticeable flickering in the screen for a very short time probably due to the dynamic change of CSS properties. However this does not happen in case of Safari on iOS 13.

I hope this is useful. 
Thanks.

**Comment by dhilt** [comment]
@ateto Thanks a lot! Your code reminded me of my own tries to implement similar approach. It is not in use, but perhaps it would be meaningful to revisit it and provide an option allowing to remove scrolling ability from the viewport while rendering new rows expanding the upper edge of the viewport.

https://github.com/dhilt/ngx-ui-scroll/blob/8af76d1e01a17cfdd941f3312095187c991481dc/src/component/classes/viewport.ts#L81-L96

The last thing I want is to make any platform-specific patches, but providing such an option could be a good compromise...

PS Your min/max calculations are fine for an unlimited dataset, but would not take into account the limited dataset edge cases. I just want to announce the [new API](https://github.com/dhilt/ngx-ui-scroll/issues/236) that might be useful for this purpose.
