### ISSUE TITLE
Dragula compatibility issues

### ISSUE THREAD

**Issue by vazz3rt** [dhilt/ngx-ui-scroll#215]
Hello,
when replacing *ngFor with *uiScroll, dragula starts to behave incorrectly. I've created two examples picturing the issue:
1. ngFor version: https://stackblitz.com/edit/ngx-ui-scroll-4ojtsc?file=src%2Fapp%2Fapp.component.html
2. uiScroll version:  https://stackblitz.com/edit/ngx-ui-scroll-rkj2s1?file=src%2Fapp%2Fapp.component.html

**Comment by dhilt** [comment]
@vazz3rt Here's the fixed demo: [ngx-ui-scroll-dragula](https://stackblitz.com/edit/ngx-ui-scroll-dragula). I did few changes, the major ones are:

 - provided viewport element via `{ settings: viewportElement: () => document.querySelector('.viewport') }` -- see [documentation](https://dhilt.github.io/ngx-ui-scroll/#/experimental#viewportElement-setting) for more details
 - removed inversion logic from the datasource implementation because of the initial data array inversion

I see 25px shift after the initial render, it seems a bug of the viewport margin processing. I didn't research it for now, perhaps we may create a separate issue for it. But as a workaround you may remove margin if the UX allows OR provide auto-scrolling to zero position right after the initial render.

Anyway, thanks for raising the interesting case, I hope this helps and I would be glad to continue the discussion.

**Comment by vazz3rt** [comment]
@dhilt thanks for quick response! Main issue is inability to reorder list elements with D&D, which persists sadly in fixed version. When *uiScroll is used, whole list moves in drag, instead of one element. It seems that Dragula detects uiScroll containter as element designated to be dragged, because it's directly under element with `[dragula]` directive, when whole thing is rendered.

**Comment by dhilt** [comment]
@vazz3rt Oh I see, you are right, nested elements break the flow. The template `<c1><c2 *uiScroll="..."></c2></c1>` is being compiled into 

```
<c1>
  <div ui-scroll>
    <div data-padding-backward></div>
    <div><c2>...</c2></div>
    <div><c2>...</c2></div>
    <div><c2>...</c2></div>
    ...
    <div data-padding-forward></div>
  </div>
</c1>
```

All of the design issues could be resolved via css. But if you need to provide some Angular specific bindings with `<div ui-scroll>` element... that's the problem because this element is dynamic and you have no access to it at the component's template level.

I briefly looked into [dragula native doc](https://github.com/bevacqua/dragula#dragulacontainers-options) (not ng2-dragula), it seems they suggest dynamic initialization

> The example below allows the user to drag elements from left into right, and from right into left.
> ```js
>dragula([document.querySelector('#left'), document.querySelector('#right')]);
>```

I would say that it would be the most straightforward solution: 
 - wait for the Scroller is rendered
 - initialize Dragula by passing `<div ui-scroll>`  reference as a container

ng2-dragula may have no such functionality because this is a bit out of declarative way and serves quite complex and specific use case, you may check this and raise the issue if you want to go with ng2-dragula. Or try native dragula instead.

Another option is to think how we can achieve this on the ngx-ui-scroll end. Right now I have no vision how to do it. This can't be done quickly.

PS You also should take into account virtualization padding elements (data-padding-bachkward and data-padding-forward), they must be excluded from the flow. As I see native dragula allows this via [moves](https://github.com/bevacqua/dragula#optionsmoves) and [accepts](https://github.com/bevacqua/dragula#optionsaccepts) options.

**Comment by vazz3rt** [comment]
I was able to make it work using dynamic initialization by using following solution
in template:
```
<ul #scroll>
   <li *uiScroll="let el of datasource">
      <div>element content</div>
   </li>
</ul>
```
in component:
```
@ViewChild('scroll') scroll!: ElementRef;
ngOnInit(): void {
   this.dndService.drake.containers.push(this.scroll.nativeElement.firstElementChild);
}
```

**Comment by dhilt** [comment]
@vazz3rt Great news! You made it with native dragula, correct? It would be nice and very helpful for others if you could publish your solution on stackblitz

**Comment by dhilt** [comment]
Closing this, as the original issue had been resolved. Also, here is the demo for drag-and-drop functionality built on top of the "angular/cdk/drag-drop": https://stackblitz.com/edit/ngx-ui-scroll-drag-and-drop.
