### ISSUE TITLE
data source update flicker

### ISSUE THREAD

**Issue by urielTwito** [dhilt/ngx-ui-scroll#233]
I am trying to do master slave UI here is the demo 
https://stackblitz.com/edit/angular-ivy-1o4kap?file=src%2Fapp%2Fapp.component.ts

the problem I have is when ever I click on different customer then we see the items flickering (it is like the controls are destroyed and created again)

it probably happens because I do this. (call reload)

```
  select(value: string) {
    this.updateCustomer(value);
    this.customerDataSource.adapter.reload();
  }
```

is there a way to refresh the data without reload?

pay attention that I even do not create a new list I just update the current list.
is there away to notify the UiScroll just to update the list (something like change detection)

**Comment by dhilt** [comment]
@urielTwito This definitely happens because of `reload`. Instead, you need to have a sort of direct access to the scroller's buffer, and you may use experimental [fix-updater](https://dhilt.github.io/ngx-ui-scroll/#/experimental#adapter-fix-updater) API for this purpose:

```ts
    this.updateCustomer(value);
    this.customerDataSource.adapter.fix({
      updater: ({ $index, data }) =>
        Object.assign(data, this.customerFullData[$index])
    });
```

Here we have two synchronous processes: updating the datasource (`updateCustomer`) and updating the scroller's buffer on flight (`customerDataSource.adapter.fix`). Assuming the natural indexes of the datasource are consistent with the internal indexes of the scroller, you may just replace the contents of the items of the scroller's buffer by `$index`, which is an argument of the adapter-fix-updater callback. Updater provides access to `data` which keeps original reference to the item's data object which is bound with the template. `Object.assign` allows to persist this reference and we can perform the update directly. Change detection is not involved!

If you're expecting dimension changes after updating the contents, you may call [adapter.check](https://dhilt.github.io/ngx-ui-scroll/#/adapter#check-size) to maintain viewport's params consistency.

**Comment by urielTwito** [comment]
Thanks @dhilt  it works great!!
I do expect dimension change, I wonder were should I call this function , is it good to call it after the ```fix promise``` has fulfilled?

**Comment by urielTwito** [comment]
another thing, some times I get data = undefined, is it OK should I just  be undefined safe?

```
  select(value: string) {
    this.updateCustomer(value);
    //this.customerDataSource.adapter.reload();
    this.customerDataSource.adapter.fix({
      updater: ({ $index, data }) => {
        if (data) {
          Object.assign(data, this.customerFullData[$index]);
        }
      }
    });
  }
```

**Comment by urielTwito** [comment]
another question: if both lists have different number of elements, how can I refresh the list in that case?
should I use reload (and get flickers)?

**Comment by dhilt** [comment]
@urielTwito **1.** You should run `Adapter.check` when the view is changed, and `Adapter.fix` promise will not help you, because this method is synchronous. You may use [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) or any other technique allowing to watch the DOM changes. From the other hand, if you are sure the view will change in the nearest timeframe after the `fix` and you are fine with `setTimeout`, you may try to use `setTimeout(() => this.ds.adapter.check(), 0)` ... anyway this is a developer responsibility, the lib just provides API.

**2.** If your datasource does not imply `undefined` items, I would say that `undefined` in the `updater` callback is a bad sign. But the first thing I'd suggest in such algorithm is to protect it by the `relax` promise:

```js
async select(value) {
    const { adapter } = this.customerDataSource;
    await adapter.relax(); // to be sure the scroller is not running any internal processes
    this.updateCustomer(value);
    adapter.fix(...);
}
```

**3.** Basically you are talking about two different datasources, which should have two different representations. With two different instances of the Scroller. You may hide/show them via standard UI techniques, like tabs switching. Of course, if you want them to be live permanently, there will be some scroller-specific issues, because the Scroller requires a visible are of fixed height to fetch and render rows, so you can't just ng-hide the second viewport on start... This is a good task, and I have no appropriate demo. But if I were in your position, I would try to keep it as separate as possible. It seems very unnatural and hardly maintainable to have 2 datasources as 1. 

If you will decide to go with 1 Scroller instance, I would recommend use [reset](https://dhilt.github.io/ngx-ui-scroll/#/adapter#reset), not reload, to eliminate any interferences on the lib's end when switching. "Reset" allows you to have 2 datasources with only 1 Scroller which silently re-instantiates itself each time you need to replace the datasource.

**Comment by urielTwito** [comment]
@dhilt  thank for the fast response.
look at the example don't click on any customer, just scroll to the end of the list.
then look at the console, can you explain the errors?
https://stackblitz.com/edit/angular-ivy-1o4kap?file=src%2Fapp%2Fapp.component.html

**Comment by dhilt** [comment]
@urielTwito Datasource.get obviously pushes `undefined` to the result `data` array which breaks the flow in your case. It is caused by incorrect indexes calculations: the max possible index is not array.length, it is array.length - 1:

```js
const end = Math.min(index + count - 1, this.customerFullData.length - 1);
```

**Comment by urielTwito** [comment]
thanks @dhilt  it works!!, I integrated it in my application it solved my performance problems.
