### ISSUE TITLE
Access item at index in buffer and get scroll direction

### ISSUE THREAD

**Issue by hmobs** [dhilt/ngx-ui-scroll#240]
Hey.
I'm trying to use this library with live data from firebase.

Perhaps it is my limited understanding of the library, but I feel like `datasource.get` is complicating this specific use case.

Ideally, I would get the following:

the ui-scroll tells me:
"I am requesting X items in the forward direction, starting from the item at index Y" (ideally the data for the item at index Y would be accessible),

OR

 "I am requesting X items in the backwards direction, starting from the item at index Y"  (ideally the data for the item at index Y would be accessible)

I can then check if I have the items to fulfil this request locally, or expand my call to firebase to get the items (I could do this via the observable or promise signatures for datasource.get).

What I'm missing to be able to do this is:
Direction of items requested (count and index doesn't infer direction)
Data of the item at the index that is being provided in datasource.get

My understanding is that I have no way to get these currently. Is my approach to linking this up to firebase feasible? Any ideas for an alternative method?

**Comment by dhilt** [comment]
@hmobs Thank you for your questions, not sure if I understood it properly, but I will try to answer. 

The Scroller requests items by index ascending only. If he decides he need Y items before X index, he calls `Datasource.get(X - Y + 1, Y)`, so you shouldn't take care of direction. Unless you are going to implement a [reversive Datasource](https://dhilt.github.io/ngx-ui-scroll/#/datasource#inverted-indexes). But this case, you see, is a kind of fake flow, because we are cheating the Scroller, as he would think that his request is ascending.

On items data access. Right now there's only one simple way to get access to all items in current Buffer at runtime: [Adapter fix-updater API](https://dhilt.github.io/ngx-ui-scroll/#/experimental#adapter-fix-updater). For example:

```js
getDataByIndex(index) {
  let result;
  this.datasource.adapter.fix({
    updater: ({ $index, data }) =>
      $index === index && result = data
  });
  return result;
}
```
