### ISSUE TITLE
adapter.replace limitations / trackBy support for *uiScroll

### ISSUE THREAD

**Issue by vbraun** [dhilt/ngx-ui-scroll#245]
This was discussed in #150, but there is an important piece of information missing there. The trackBy is not just a performance optimization. DOM elements have state, perhaps most importantly the focus state. In particular, if virtual scroll items contain input elements then you really want to preserve focus if that item didn't change.

Right now, if the datasource changes then you apparently have two options:

* use adapter.replace, which creates new Item wrappers around the data (even if only the index of the data element changed). Since the underlying ngFor has no trackBy, the DOM elements are destroyed and recreated, and focus is lost. On the plus side, this method supports templates with OnPush.

* use adapter.fix to replace the data object attributes without changing its identity. Still can't preserve focus if the index changes. Does not work with OnPush templates (this is undocumented and took me way too long to figure out). Requires the data object to be mutable (no Object.freeze as e.g. ngrx store likes to do). And I'd say is in general a giant foot-gun.
 
I think it would be useful if one could supply a trackBy function for the internal ngFor. It probably should fall back to tracking by Item.data identity if it is not supplied (not: Item identity, which it is now).  

I tried to add it to the UiScrollComponent, but that did not work at all. Its pretty clear that vscroll gets confused with the view model Item order vs. the DOM children order if angular reorders/recycles the latter. In particular Item.element doesn't seem to point to the right element, and lots of children with `display: none` are created.  Looking around a bit I noticed that there is Routines.hideElement doing direct DOM manipulation but no showElement so thats probably to be expected.

Not sure if there is anything that can be done about it, I just wanted to write up my findings. In my use case I could so far kludge around it with the adapter.fix method but I'm not sure if we run into that limitation again in the future.

**Comment by dhilt** [comment]
@vbraun Thanks! I created demo: https://stackblitz.com/edit/ngx-ui-scroll-2-0-0-angular-11-focus-issue. Both cases more or less work: Replace case has ".focus" workaround, Fix case just works. I believe I didn't get it properly, and I would ask you to update the demo to make it more clear. What index you did mean for the Fix case? Internal $index can't be changed with the Adapter.fix method, while any custom props of the item's data are being applied "as is" even if OnPush is enabled (see demo). I agree, Adapter.fix-updater approach is dangerous, that's why it is an experimental feature, but it should work properly in this case and I want to be sure with it.

The idea of tracking-by item's data is very interesting... not sure if I clearly understand how it should work in the end, but I would comment what you have already tried. Hiding the elements via display-none happens when

 - resetting the Datasource via Adapter.reset
 - clipping items via standard workflow (Clip process in [this diagram](https://github.com/dhilt/ngx-ui-scroll/wiki/The-UIScroll-Workflow))

In both cases it is needed only to reduce potential blinking and measurement errors before the items are actually removed from DOM. Scenario is as follows: Scroller's Workflow (WF) decides to remove some items -> WF hides them via display-none -> WF makes calculations and updates Buffer.items -> UiScrollComponent runs detectChanges -> Angular removes elements from DOM. The fact you see hidden but not removed elements in DOM means you make some step broken. Hiding must automatically precede removing. Hidden items must never be re-shown.

We may try to make another online demo. Since v2 it is quite simple to move all ngx-ui-scroll sources (just 5 small files) to stackblitz and play around UiScrollComponent. But if it is going to affect the core, only standard git collaboration will work and I would happily see the PR ([here](https://github.com/dhilt/vscroll)) and elaborate it.

**Comment by gaoyajiang** [comment]
When I use  this.datasource.adapter.reload(20) to slide to the 20th item，then slide up again,  the first to 19th items are not loaded....I created demo:  https://stackblitz.com/edit/angular-ivy-mgctqr?file=src%2Fapp%2Fapp.component.html

**Comment by vbraun** [comment]
Fixing up focus by calling element.focus() after having lost it is fraught with cross-platform issues. In particular on iOS / safari mobile you can only programmatically focus an element from within the stack frame of a touch handler. In our case updates are also being pushed from firebase, if that happens the browser does not allow it and focus is lost. Potentially that means the keyboard closes while you are typing.

But that was only one of many examples of state. Others are
* Animation counters: Recreating a dom element restarts the animation
* Images flicker sometimes: his is very dependent on browser and timing, but recreating img nodes (even with the same src attribute) sometimes causes the image to not render for a frame, which manifests itself in a flicker.

For the OnPush problem with adapter.fix I edited the demo here:  https://stackblitz.com/edit/ngx-ui-scroll-2-0-0-angular-11-focus-issue-tk5glw
Note that angular implicitly runs a change detection when the component receives a click event (even with OnPush), so I added a setTimeout in the click handler to delay calling adapter.fix. The change is not displayed after the setTimeout, but the child component is refreshed when you click on it again. So it looks like the initial click is not working, but subsequent ones are (because after the n-th click it shows n-1 stars)

**Comment by dhilt** [comment]
@vbraun I appreciate so detailed explanation of why you don't want the DOM elements to be re-created. And this would be great challenge to try `trackBy` data in some way... maybe you can share your efforts?

Speaking of your demo, I can suggest the following rough workaround. Add subsidiary callback to Item:

```ts
export interface MyItem {
  id: number;
  text: string;
  onChanged: () => void;
}
```

Provide detect changes via this callback:

```ts
export class ChildComponent {
  private _item: MyItem;
  @Input() set item(value: MyItem) {
    value.onChanged = () => this.changeDetector.detectChanges();
    this._item = value;
  }
  get item(): MyItem {
    return this._item;
  }
  constructor(public changeDetector: ChangeDetectorRef) { }
}
```

And run change detection when time:

```ts
  async processRowFix(item: MyItem) {
    await this.datasource.adapter.relax();
    this.datasource.adapter.fix({
      updater: ({ data }) => {
        if (item.id === data.id) {
          data.text += "*";
          item.onChanged();
        }
      }
    });
  }
```

Also, in rc.6 I added the second argument to the `Adapter.fix-updater` API which [refreshes Buffer.items reference](https://github.com/dhilt/vscroll/commit/c198fc0c956a4333f1802a0b31b0a4bd2201d975#diff-09fc3f4bb1fe44187a012fdd57999c6007ae7efd726ab0bc8e6c4f3ef2cce8c1R77-R84) and can be useful when immutability is the matter. Basically it works as follows:

```js
this.datasource.adapter.fix({
  updater: ({ data }, update) => {
    if (item.id === data.id) {
      data.text += "*";
      update();
    }
  }
});
```

But in your particular case it will not help due to separate Item sub-component with onPush. Just FYI.
