### ISSUE TITLE
loss of elements while loading new element

### ISSUE THREAD

**Issue by amirhosein993** [dhilt/ngx-ui-scroll#246]
Hi. I am using your great module for my chat app. I faced a problem on loading new buffered elements. I lose a message on the edge. It performs like a jump through. 
Its annoying for users. 
how can I fix it? 
elements (messages) have margin top from each other and don't have constant height.

**Comment by dhilt** [comment]
@amirhosein993 Thanks for using the lib! The best option would be to make a demo by forking [this stackblitz latest starter sample](https://stackblitz.com/edit/ngx-ui-scroll-2-0-0-angular-11) or maybe [this chat sample](https://stackblitz.com/edit/ngx-ui-scroll-chat-app-2), which is more complex but should be closer to real life. There is a big margin of discretion in DOM-Datasource-Scroller stack, which may lead to very specific cases and issues that should be considered separately, and runnable demo is the most easy and fast way for me to deal with your case!

**Comment by amirhosein993** [comment]
Thanks. I am using append and prepend to handle scroll down and scroll up messages. For virtualization I used all relax(), reload(specificIndex) and fix() methods. and jump happens as I said. 
I'm sorry I can't share the code on stackblitz (in org privacies) but the logic of datasource get method is like your chat application example. 

> @amirhosein993 Thanks for using the lib! The best option would be to make a demo by forking [this stackblitz latest starter sample](https://stackblitz.com/edit/ngx-ui-scroll-2-0-0-angular-11) or maybe [this chat sample](https://stackblitz.com/edit/ngx-ui-scroll-chat-app-2), which is more complex but should be closer to real life. There is a big margin of discretion in DOM-Datasource-Scroller stack, which may lead to very specific cases and issues that should be considered separately, and runnable demo is the most easy and fast way for me to deal with your case!

**Comment by dhilt** [comment]
@amirhosein993 Oh, you don't need to replicate your App code base, you need just to build a minimal reproducible demo. Anyway, using `append` and `prepend` Adapter API seems like an overcomplicated approach, if we are talking about fetching/displaying data by scroll events. Handling of the scroll events is a `Datasource.get` responsibility, while the Adapter API could be most useful when there are new messages in the remote storage that had never been there before the App initialization or User decides to remove some message or... any other action but scrolling. This doc contains the details of what I'm talking about: https://github.com/dhilt/ngx-ui-scroll/wiki/Chat-App.

Losing an item looks like an issue with the internal indexes consistency, which is usually caused by not perfect `Datasource.get` implementation OR by lack of synchronisation of changes made by the Adapter API with the Datasource (a few more words on such synching [is here](https://dhilt.github.io/ngx-ui-scroll/#/adapter#append-prepend-sync)). This means that I can only help in theory (I think I did it), and I need to see the details of your App-Scroller communication layer to help you practically.
