### ISSUE TITLE
scroller jumps back to start when using maxIndex and the size is too large

### ISSUE THREAD

**Issue by deeg** [dhilt/ngx-ui-scroll#261]
**Issue**

- Use maxIndex 50011
- Use item size of 20px
- Scroll to the very bottom. Notice it jumps back to the top.

ngx-ui-scroll v1.11.1, Angular v11.2.0

**Stackblitz**

https://stackblitz.com/edit/angular-ngx-ui-scroll-pages-api-iq2hap?file=src/app/app.component.ts

**Video**

[Video Link](https://drive.google.com/file/d/1x6ukO0sz9pkv6AWvpia0kUde-iAT4wU9/view?usp=sharing)

**Cause**

this.paddings.backward.size is set to 1

![image](https://user-images.githubusercontent.com/2857769/113786305-b8656380-96ed-11eb-961c-fa83fcbc63c7.png)

Seems to be when the scroller gets to be around 1,000,000 px

![image](https://user-images.githubusercontent.com/2857769/113786431-f82c4b00-96ed-11eb-990f-598f0d0928b2.png)

I will continue to look around and see if I can publish a PR, but wanted to report incase anyone had a quick solution / answer.

**Comment by dhilt** [comment]
@deeg This is very very interesting issue, thanks you! I will investigate it in a few days. If you'll be able to find the cause and suggest PR, that would be great, but there might be some infrastructure difficult. The point is the library (ngx-ui-scroll) is about to v2 release (it is 99% ready), and the main change is that the core is going to be a separate npm module (vscroll). Master branch is already switched to v2-rc.10 with "vscroll" dependency, so the fix should be done on the vscroll's end: https://github.com/dhilt/vscroll. Local development should take this into account and there is no strict guide for this. Currently I'd recommend the following:
 - clone both projects (ngx-ui-scroll, vscroll) into the same level
 - update this link to get vscroll from the local repo rather than "vscroll" npm module:  https://github.com/dhilt/ngx-ui-scroll/blob/bc1df432e0d63657c596d5accfb804a9a96f6c46/src/vscroll.ts#L17
 - the same change should be done in tests: https://github.com/dhilt/ngx-ui-scroll/blob/bc1df432e0d63657c596d5accfb804a9a96f6c46/tests/miscellaneous/vscroll.ts#L16

**Comment by deeg** [comment]
@dhilt , I haven't had time to look at it yet, but I might have time early next week.

Did you happen to make any progress with it?

I am currently on v8 of Angular in the application where I'm using the library. Does the v2 version of this library still work with that version of Angular? When I first installed your package, I think I had that beta version and I saw errors.

I hadn't looked into what those errors were yet, since I realized I wasn't using your latest stable version.

If it does not work with Angular v8 would you consider pushing a fix onto the v1 version of this library?

**Comment by dhilt** [comment]
@deeg ngx-ui-scroll v2 was released 5 days ago, yes it works with Angular 8, please check and let me know if you have any problems. I didn't look it the issue you raised (busy with vscroll-Vue integration).

**Comment by dhilt** [comment]
I found it. [Here](https://github.com/dhilt/vscroll/blob/v1.0.0/src/classes/domRoutines.ts#L61-L65) the padding element's height is read as an integer:

```ts
 parseInt(size as string, 10) || 0;
```

When the height is less than 1M px, it is written in standard notation. When it is more than 1M px, it is written via exp. (Chrome 89)

```
element.style.height = '999999px';
console.log(element.style.height); // "999999px"

element.style.height = '1000000px';
console.log(element.style.height); // "1e+06px"
```

Parsing the last value as an integer just results in `1`. This must be parsed as a floating point number. I need to investigate whether it needs to be rounded or not and then will release a patched version.

**Comment by dhilt** [comment]
@deeg Please try ngx-ui-scroll v2.0.2, this should be done.

**Comment by deeg** [comment]
@dhilt , I will try it out today or tomorrow and get back to you! Thanks.

**Comment by deeg** [comment]
@dhilt , it is working as expected, thanks or the quick fix!

I am seeing some issues with the reset call, but I'm not certain if I need to adjust to any changes made from the version jump.

I will try to re-create in a demo project and if I see any issues open a separate bug.

Will close this as fixed!
