### ISSUE TITLE
Card like "list" layout

### ISSUE THREAD

**Issue by taujoey** [dhilt/ngx-ui-scroll#267]
Hi,

I have been using your virtual scrolling implementation for a while now with a "simple" list, works great.
Now, I would like to extend my UI with a card-like layout, what is basically just putting several boxes (cards) in the same row, instead of using like a "simple" (actually normal :) ) list, where 1 row = 1 element. Now it woudl be (1 row = n elements), where "n" depends on the width of the cards, and  e.g. the zoom level of the browser. So what I want is basically what you can see on e.g. the youtube main page, when you scroll down.
I used the FlexLayoutModule to quickly place the cards, and of course I would like to use the feature of the virtual list, where it fetches new data, when scrolled to a specific point. Problem (i think) is pretty trivial, when we have multiple items in a row, the itemsize should be the calculated averege's divided value by the number of items in a row, to be able to trigger a fetch (at least that is my initial feeling). I tried using "constant" size strategy, but could not figure it out.

Is there any easy way to implement this with the current codebase (small extra parameter for division, or smg else), or is it a totally stupid idea? (My gut tells me it could be done pretty easily with the current codebase, but i dont know how).

Thanks!

**Comment by dhilt** [comment]
@taujoey Hi! If you have a fixed number of items in a row, you can solve the problem by adding an intermediate grouping layer between the Scroller's Datasource and the App linear data source. The Scroller's Datasource can consume groups of items instead of items:

```html
<div class="viewport">
  <div  class="group" *uiScroll="let group of groupsDatasource">
    <span class="item" *ngFor="let item of group.items">
      {{item.text}}
    </span>
  </div>
</div>
```

Here's one of the possible implementation of the grouping approach: https://stackblitz.com/edit/angular-ngx-ui-scroll-grouping-2. 

If you need a responsive layout (number of items can change per changing the viewports size), you may turn this sample into a dynamic one by listening to viewport's width change and re-grouping the linear data at runtime. This may require invalidating the internal Scroller's cache from the outside, we have no such API, but it could be added.

**Comment by taujoey** [comment]
@dhilt Thanks for the suggestion, i tried playing around with this in the last few days, but it seems a little complicated (comparing to a simple "flex" like behaviour). I'll try to rewrite my code to base it on group indexing instead of item indexing (with 1 element groups in case of "normal" list view, and keeping an own local cache to minimize calling toward the backend), and get back to you about that cache invalidation, when i see what that means actually :)
Thanks!

**Comment by dhilt** [comment]
@taujoey I implemented simplest "flex" case over the previous "grouping" demo: **https://stackblitz.com/edit/angular-ngx-ui-scroll-grouping-flex**. I realized, Cache invalidation is not needed because of fixed group height, though there still might be issues... maybe it would be better to use Adapter.reset instead Adapter.reload. Also, Adapter.reset will allow to play with min/maxIndex settings at runtime and persist scrollbar params through re-grouping. But I think the big part of the job is done and I'd be glad if you confirm it.

**Comment by taujoey** [comment]
@dhilt Looks very good, thanks! :) I'll take a look (unfortunatelly i progress slowly beside my day job), but it works as i expected. :)
I played around with it a little, i scrolled to few hundred, and started zooming in and out, and i see mostly the previously present item is there after zooming, but the list starts to slide toward the beginning (btw this is the same logic i was now working on, how to keep the scroll position after zooming, really tricky).
Also, this happened 1 time on firefox:

![image](https://user-images.githubusercontent.com/4067528/120079012-b353dd80-c0ba-11eb-824c-ba98e3d7d033.png)

It might be some corner case, i don't know, it's the devserver on stackblitz. 
I'll import your solution into my project, and check with chrome too.

Thanks, it's great! :) 👍

**Comment by dhilt** [comment]
@taujoey The screenshot says that the calculations are not precise enough. The approach should be tested and fixed again and again before using in prod.

The problem of scrollbar params persistence across the reload was mentioned in the previous comment. I suggested to use Adapter.reset instead of reload. The point is that when you do resize (causing re-grouping), you know how many items the Scroller dealt with, and you may set `minIndex` along with `startIndex` as params of `Adapter.reset` call... This will force the Scroller to virtualize all the rows between "min" and "start", and you'll see correct scroll position.

**Comment by taujoey** [comment]
Based on your suggestion I managed to put together a pretty good working poc, thanks for that!
Although i have a little problem with "the grouping layer above the single items" and another use case regarding the EOF state of the dataset. I will create another issue for new feature request or enhancement, so this can be closed, if You think so :)

Thank You!

**Comment by dhilt** [comment]
Sounds good! To summarize, we have the following card-like-list demos:
 - [simple grouping](https://stackblitz.com/edit/angular-ngx-ui-scroll-grouping-2), fixed number of items per row
 - [flex grouping](https://stackblitz.com/edit/angular-ngx-ui-scroll-grouping-flex), row capacity is dynamic and depends on the viewport size
