### ISSUE TITLE
I am working with angular , but it is not working on C# API please help me

### ISSUE THREAD

**Issue by thananhtuan2011** [dhilt/ngx-ui-scroll#274]

**Comment by dhilt** [comment]
@thananhtuan2011 Basically, ngx-ui-scroll is designed to work in the Angular environment, no matter what sup-environment is consuming Angular. Your stack, as I got, is as follows: **.NET** -> **Angular** -> **ngx-ui-scroll**. And I believe your issue is the problem of **.NET** -> **Angular** part of the stack. I never dealt with **.NET** - **Angular** communication in my practice, so I have no relevant knowledge. You've certainly seen the official docs, like [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-5.0&tabs=visual-studio) (especially something related to using third-party libraries, like ngx-ui-scroll), but that's all I can refer to.

But if you are experiencing any sort of **Angular** -> **ngx-ui-scroll** specific issues, please post correspondent details. It must only relate to the web frontend.
