### ISSUE TITLE
Items with webcomponent Shadow DOM are not fetched correctly

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [dhilt/ngx-ui-scroll#294]
First of all, thank you for a very nice and well documented library that is a pleasure to use. 

I am trying to use this library for virtualising a list of items that are web-components. As documented in [this stackblitz](https://stackblitz.com/edit/angular-ivy-ppnmpb), I am seeing issues when using a web-component that has a shadow dom. 
It works if I wrap it in a `<div>` with a specified height, but that is not ideal in my use case, where items can have many different heights.

It seems to only load the inital buffer, before failing to fetch the rest of the data. I have previously been playing around with wrapping the get method in a setTimeout call, which seemed to work in some cases. Unfortunately, I cannot replicate that behavior in stackblitz.

A curios thing is - sometimes when making changes in the stackblitz-example it seems to work as expected after hot-reloading. But it only works until the page is refreshed and the project is built from the ground up again. 

Any pointers as to what might be the issue?

**Comment by dhilt** [comment]
@RasmusKjeldgaard Do you know the exact moment of time when your components are loaded and rendered? If no, you may try to implement your own process of detecting such changes via [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) or any other native or framework API matching your situation. Then call the Adapter.check method:

|Name|Parameters|Description|
|:--|:----|:----------|
|[check](https://dhilt.github.io/ngx-ui-scroll/#adapter#check-size)| |Checks if any of current items changed it's size and runs a procedure to provide internal consistency and new items fetching if needed. |

Does it help? I would love to see you demo fixed, because it may be useful for others.

**Comment by RasmusKjeldgaard** [comment]
@dhilt Thank you for getting back so quickly. Right now I can't see a feasible way to hook into the web-components lifecycle (in this case Ionic components, but could be anything), so I will try and investigate the MutationObserver path for a more generalised and natively supported solution, and get back to you with my findings.

**Comment by dhilt** [comment]
@RasmusKjeldgaard Here's a little demo of viewport resizing: [ngx-ui-scroll-change-viewport-size-in-real-time](https://stackblitz.com/edit/ngx-ui-scroll-change-viewport-size-in-real-time). The point of this demo is that we need to trigger scroll event on manual resize to provide consistent flow, because expanding of the viewport might require new items, and scroll event forces new items fetching. Of course, your case is more complicated: you need to set up such process for each row.

What I think; if each row is a child-component with its lifecycle hooks, perhaps it would possible to ping the parent on render using standard Angular API. Parent knows how many child-rows should be rendered, and when all the children have reported, it runs Adapter.check.
