### ISSUE TITLE
How to use Ngx UI Scroll with Ngrx?

### ISSUE THREAD

**Issue by GitHubish** [dhilt/ngx-ui-scroll#306]
I can't see how I could use the Ngrx mechanics with the effects with this library to do the lazy loading of my data to display ? Any idea how to help me? I imagine that other people might be interested

**Comment by dhilt** [comment]
@GitHubish Could you please post a draft demo on stackblitz (by forking [this one](https://stackblitz.com/edit/ngx-ui-scroll-2-angular-12) for example) with your vision of Ngrx usage? I would expect to see: 1) all necessary Ngrx infrastructure, 2) example of Ngrx usage in the App (not in context of Scroller), 3) some thoughts on integration with Scroller (by code or comments). Then I'll take a look and suggest an approach. I'll fix your demo and will ask for feedback.

~~Basically, the integration should be done on the `Datasource.get` level. It should pro-actively asking Ngrx for appropriate chunks of data, I guess.~~  Upd: see below!

**Comment by fabioemoutinho** [comment]
@dhilt I'm trying to use NGX UI with NgRx.
In NgRx, if there is an event of adding one item to an NgRx collection, the observable (selector) emits a new array with all items.
I don't think `get` is the proper method for a long-lived observable as `get` expects only one emission.
Considering you had a long-lived observable that emits the entire collection every time there is a change, what would be the best approach to adding/updating data to `datasource`?

**Comment by dhilt** [comment]
@fabioemoutinho Thanks for the question, below is a detailed explanation of how I see the situation with an external data source changing in runtime.

**1.** If the entire collection is changed and becomes incompatible with the previous one, the best approach, I guess, would be to reset the Scroller ([link](https://dhilt.github.io/ngx-ui-scroll/#adapter#reset)):

```ts
this.datasource.adapter.reset(new Datasource(...));
```

The view will be rebuilt, which seems right if all the data has changed.

**2.** In case the collection update is not total, you need to consider merging it with an existing data source (2.1) and providing these changes to the current view (2.2).

2.1. If your `Datasource.get` implementation relies on a separate data array (e.g. copy of ngrx-emitted data), you need to update it first, because the `Datasource.get` method is a source of truth for the Scroller, and its index-based data flow must be perfectly synched with your changes.

2.2. There are a bunch of Adapter methods allowing on-flight updates without resetting the view. If the update may affect virtual items that are not present in current Scroller's buffer, you may use [insert](https://dhilt.github.io/ngx-ui-scroll/#adapter#insert), [remove](https://dhilt.github.io/ngx-ui-scroll/#adapter#remove), [append](https://dhilt.github.io/ngx-ui-scroll/#adapter#append-prepend) and [prepend](https://dhilt.github.io/ngx-ui-scroll/#adapter#append-prepend) methods of the Adapter. If the update affect only current in-buffer items, you may also use [replace](https://dhilt.github.io/ngx-ui-scroll/#adapter#replace) and [update](https://dhilt.github.io/ngx-ui-scroll/#adapter#update) methods.

So, when you detect the external changes (by ngrx subscription), you need to
 - make sure that the Datasource.get will provide updated data when it is requested by the Scroller;
 - push these changes to the Scroller via appropriate Adapter methods to statically fix the view (scrollbar params or/and existed items view).
 
If you could provide a working demo, I would review it if necessary.

**Comment by fabioemoutinho** [comment]
@dhilt thanks for the quick response!

So, in an NgRx Store, you don't exactly have the information on what has changed, you get instead a new state, and the change detection does its magic to update the UI.

After reading your response, I think the best approach is to use NgRx Effects to trigger adapter methods (like insert, remove, append and prepend) either through a service or some other way.

I'll be happy to share my approach once I get it working (probably by the end of next week) and would highly appreciate your feedback on it. Hopefully, this might help others trying to integrate NgRx with ngx-ui-scroll in the future.

**Comment by fabioemoutinho** [comment]
@dhilt this is my attempt at integrating with ngrx: https://github.com/bitovi/angular-ngrx-chat/tree/virtual-scroll

I was not able to understand why Scroller does not attempt to fetch items with an id greater than 1

https://github.com/bitovi/angular-ngrx-chat/blob/virtual-scroll/src/app/chat/chat.component.ts#L48

**Comment by dhilt** [comment]
@fabioemoutinho Please, give me push access to your repo, we'll do things in a branch, and when is it done, I'll post it in stackblitz.

**Comment by fabioemoutinho** [comment]
@dhilt I created a fork and invited you: https://github.com/fabioemoutinho/angular-ngrx-chat. feel free to commit in any branch. Thanks

**Comment by fabioemoutinho** [comment]
and let me know if you want to communicate in any other way. I'm available to use the tool you prefer to communicate with.

**Comment by dhilt** [comment]
@fabioemoutinho It is done, please look at these [Files changes](https://github.com/fabioemoutinho/angular-ngrx-chat/pull/1/files/c0dce911b7113f8a0155204dcb613e1fde52fafa), it contains my notes, and I suggest to continue the discussion in the PR thread.
