### ISSUE TITLE
Duplicated results when dataset is smaller then bufferSize and requested index > 1

### ISSUE THREAD

**Issue by dabcat** [dhilt/ngx-ui-scroll#43]
Hi @dhilt ,

seems like this is another bug which duplicates results when dataset is smaller then bufferSize and requested index larger then one (>1).

For example:

- dataset has 5 records
- bufferSize is set to 100
- datasource.adapter.reload(2)

Rendered rows are duplicated.

Hope this makes sense, if not I'll try to setup demo.

**Comment by dhilt** [comment]
Hey @dabcat! I have created stackblitz demo that reflects your situation – https://stackblitz.com/edit/angular-bicp9m – the only moment I see is 2-steps completion of the viewport after reload(2) is called. But this is designed behavior, and we have 2 requests:
 - first request that retrieves [2, 100] array and returns items `#2`, `#3`, `#4`, `#5`;
 - second request that retrieves [-98, 1] array and returns item `#1`.

After the first request is done the viewport is not filled out, that's why item `#1` takes zero position and pushes other items down by 1 row.

If it makes sense but you have another problem, I think it may be related to the Datasource implementation, so I advice you to look at how you prepare your data for the uiScroll. If the problem will not vanish, the best option to continue is to update the stackblitz demo.

Hope this helps!

**Comment by dabcat** [comment]
@dhilt here is updated stackblitz: https://stackblitz.com/edit/angular-r1hmam

`const MAX = 40`
`bufferSetting: 50`

try reloading 41 (reloadIndex)

-----------------------

Try requesting 200 (reloadIndex) in your own demo, there is a bug somewhere and it's definitely behaving very strange.

**Comment by dhilt** [comment]
@dabcat 

**Situation 1**. MIN = 1, MAX = 5, bufferSize = 100, reloadIndex = 200; what happens?
1) forward request (100 items started from 200) returns 0 items;
2) backward request (100 items started from 100) returns 0 items.

That's why the viewport is completely empty. No data had been retrieved with that Datasource and that params.

**Situation 2**. MIN = 1, MAX = 40, bufferSize = 50, reloadIndex = 41; what happens?
1) forward request (50 items started from 41) returns 0 items, that's why I see empty space in the visible part of the viewport;
2) backward request (50 items started from -9) return 40 items (from 1 to 40), they are being rendered within the invisible part of the viewport.

So, I don't see any duplicates. I agree, that the empty space seems like a bug, and I think it has to be fixed. (Though I think it could be the end-programmer responsibility, he knows the size of the dataset, he can limit the reloadIndex as well as he limited MIN/MAX.) Do you agree or you have somewhat else?

**Comment by lmreicks** [comment]
@dabcat I think your issue is the same as I was having. The 'index' is 1 indexed as apposed to 0 indexed. Try changing minIndex to 0.
