### ISSUE TITLE
Be able to specify the final size of the data set

### ISSUE THREAD

**Issue by gerardcarbo** [dhilt/ngx-ui-scroll#49]
Like in the AngularJs virtual repeater (getLength()). This way the scroll bar can be initially sized to allow an easy access to any part of the data set.

**Comment by dhilt** [comment]
@gerardcarbo Currently the uiScroll directive has no mechanism of fast jumping from one point to another with skipping intermediate rows, so all the rows between these two points will be retrieved and rendered (even if they will be immediately removed). Such skipping is very important feature and we are working on it. It will include min/max dataset indexes settings.

But for now you may try `paddingForwardSize` workaround. This is a development setting, that is undocumented and may be removed in future. (Although probably not, because it is used in the tests.)

```
   datasource: IDatasource = {
    get: this.fetchData.bind(this),
    settings: {
      bufferSize: 20
    },
    devSettings: {
      paddingForwardSize: 2000
    }
  }
```

How it works? You know your dataset length (L), you know a single item height (H) (if we are speaking about vertical scroll). So take the product of these two values: paddingForwardSize = L * H. The uiScroll will set up the bottom padding height before the first call of the Datasource.get method. This will define the height of the scrollable area. If item height is not constant, use average item height value (round it down to avoid a gap).
