### ISSUE TITLE
Chat app UI use case

### ISSUE THREAD

**Issue by bearinld004** [dhilt/ngx-ui-scroll#55]
Hello there, I'm just wondering if this plugin fits the bill to create a chat like UI. Like similar to whatsapp etc. I have spent a whole day trying a few other angular based virtual scroll and none of them fit the use case. none of them have variable height *known only during runtime, working properly. some do but the height needs to be determined before hand . And for some the array have to be mutable cannot add to the datasource have to create a new array and re-render which is not good for performance since new messages will come often while the user is chatting. And for chat UI the scroll direction is reversed and it should render from the bottom up. i dont need to worry about remote fetching all the messages will be in an array from localstorage. does this fit the bill?

Will probably experiment with this too in a few days but maybe I can get strategy or approach or maybe saves me sometime if this does not fit the bill.

Thank you!

**Comment by fperez-eypscap** [comment]
Hi, I was just about to write an issue regarding a similar use case. Kudos to the developer, I agree this is the sole project that actually works with variable height elements.
I am also fetching messages from local storage (sqlite in this case). Works great with upwards infinite scroll.
I have one only problem to overcome and it is adding new messages. When entering the page I load the most recent messages and scrollBottom. Some previous messages are fetched in order to fill the buffer. The buffer for future messages is also fetched and gets an empty array. When new messages are received there is no way to make uiScroll fetch again this messages.
The workaround I use for now is reloading to the first visible item index, but the every time this is done the screen flashes and is rerendered. This doesn't look nice, especially when there is a lot of chatting activity (even if debounce is used).
Is there any way to add a buffer reset method or similar functionality that could solve this?
Congrats again and thanks for the effort.

**Comment by bearinld004** [comment]
Ah

**Comment by bearinld004** [comment]
@fperez-eypscap

Ah nice good to hear there is some hope!

Curious and you might find this useful when you scroll to bottom of the page on load do you scroll before the last element render on your page. so you see a page thats already scrolled down already? to get this effect i think you just need to call a method that triggers once in the view template like {{callMethod()}} pop it near the end.

also on the demo momentum scrolling effects is not working well. were you able to maintain the innertia while scrolling when using mobile?

**Comment by fperez-eypscap** [comment]
Currently I have two ways of scrolling:
 - Timed using window.setTimeout.
 - Detect finish loading with window.setInterval and checking adapter.isLoading changes.
This could be improved if uiScroll raised an event (observable) when it has finished loading/rendering.

I haven't tested momentum scrolling, but you are probably right.

**Comment by dhilt** [comment]
Hi all! The issue you are describing (I mean adding items on-flight) is in the list of nearest releases features. It will look like `datasource.adapter.prepend(itemDataObject)`. Chat is very important use case, scrolling up to retrieve positive indexed items, and chat demo will be included in the demo list. 

Also, I would ask you about observable-based `isLoading`. The thing is the uiScroll uses BehaviourSubject to deliver `isLoading` to the Adapter, and the Adapter provides its value outside via `.getValue()`. Would you like to have `Adapter.isLoading` as BehaviourSubject? Please post your thoughts in a separate issue.

**Comment by bearinld004** [comment]
Got it thanks Denis!




On July 16, 2018 at 3:48 PM, Denis Alexanov
(notifications@github.com) wrote:

Hi all! The issue you are describing (I mean adding items
on-flight) is in the list of nearest releases features. It will
look like datasource.adapter.prepend(itemDataObject). Chat is
very important use case, scrolling up to retrieve positive
indexed items, and chat demo will be included in the demo list.
Also, I would ask you about observable-based isLoading. The thing
is the uiScroll uses BehaviourSubject to deliver isLoading to the
Adapter, and the Adapter provides its value outside via
.getValue(). Would you like to have Adapter.isLoading as
BehaviourSubject? Please post your thoughts in a separate issue.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
( https://github.com/dhilt/ngx-ui-scroll/issues/55#issuecomment-405404765 )
, or mute the thread

**Comment by zm3d3ni** [comment]
Any updates on chat demo? :)

**Comment by dhilt** [comment]
@zm3d3ni Thanks for the reminder! You know, the next release is going to be 1.0.0, but despite almost 100 commits difference with current `master`, there is still a lot of work ([workflow-5](https://github.com/dhilt/ngx-ui-scroll/tree/workflow-5)). Each day commit after commit we are moving to 1.0.0, and it should take a couple of weeks, I'm not sure... Right after it I will extend the Adapter to provide methods that are needed for comfortable Datasource updating on flight.

Also, there is a potential option to make and release v0.0.8 before, that will include the Adapter extension... If you would help me with testing this feature, we could try to do it. The plan could be:

 1) draft implementation in a separate branch
 2) manual testing
 3) fixes
 4) demo
 5) pull request
 6) release

2-3 may repeat, and I need help with 2 and 4. For the demo I can create stub and all necessary functionality, but I will have no time for the description and presentation... what do you think?

**Comment by Avishaidev** [comment]
There is any demo for this?
When the page is init i want to start with 20 last messages and need to start scroll at bottom.
And when i scroll up i want to load 20 more items any time.
any suggest?
Thanks

**Comment by dhilt** [comment]
@Avishaidev The behaviour you are asking for could be implemented at the `Datasource.get` method layer. There is "Inverted datasource" demo which provides one of the possible approach: https://dhilt.github.io/ngx-ui-scroll/#/datasource#inverted-indexes. If you will have questions on inverted datasource logic, I would ask you to open new issue, because this one is mostly about adding new items on-flight.

By the way, v1.0.0 is released, and there is a [PR](https://github.com/dhilt/ngx-ui-scroll/pull/79) on `Adapter.prepend` feature which is about 3/4 done.

**Comment by dhilt** [comment]
Since ngx-ui-scroll v1.0.4 had been released, we have all necessary functionality to implement Chat UI: inverted datasource logic ([demo](https://dhilt.github.io/ngx-ui-scroll/#/datasource#inverted-indexes)), Adapter.append and Adapter.prepend methods ([demo 1](https://dhilt.github.io/ngx-ui-scroll/#/adapter#append-prepend), [demo 2](https://dhilt.github.io/ngx-ui-scroll/#/adapter#append-prepend-sync)) allowing to add new items on-flight.

Perhaps it is a good idea to make big separate consolidated demo dedicated to Chat story, but I don't plan on doing in the near future. So, if the demand for this demo was take place, I would prefer to open a new issue.
