### ISSUE TITLE
list entities count

### ISSUE THREAD

**Issue by alexus85** [dhilt/ngx-ui-scroll#59]
Is there any way to get a number of entities currently being displayed on screen?

**Comment by dhilt** [comment]
@alexus85 Hi Alex! No, currently it is not possible, but we may think about how to give such an API in next releases. We already (since v0.0.6) have `Adapter. firstVisible` and `Adapter. firstVisible$` to access first visible item and it's index. I'm also going to add to the Adapter `lastVisible` interfaces. What about `count` and `countVisible` telling how many items are int the uiScroll buffer and how many items are visible on the UI respectively?

**Comment by alexus85** [comment]
yeah that would help. Thanks

**Comment by dhilt** [comment]
ngx-ui-scroll v0.0.7 is available via npm!

 - Datasource.Adapter.lastVisible.$index - index of the last visible item object
 - Datasource.Adapter.lastVisible$ - BehaviourSubject of the last visible item object
 - Datasource.Adapter.itemsCount - items that are in the uiScroll buffer, not only visible

To get only visible items you may try 
```
Datasource.Adapter.lastVisible.$index - Datasource.Adapter.firstVisible.$index + 1
```
 All these properties are still undocumented and the API could be changed in future. But I created special demo page for them: https://dhilt.github.io/ngx-ui-scroll/#/test (sources: [component](https://github.com/dhilt/ngx-ui-scroll/blob/v0.0.7/demo/app/samples/test.component.ts), [template](https://github.com/dhilt/ngx-ui-scroll/blob/v0.0.7/demo/app/samples/test.component.html)).
