### ISSUE TITLE
Adapter remove/update method

### ISSUE THREAD

**Issue by Avishaidev** [dhilt/ngx-ui-scroll#86]
There is an option to remove / update item from adapter?

**Comment by dhilt** [comment]
@Avishaidev 

**Update**

The thing is that updating items (in general) does not require any additional efforts, data changes can propagate to the uiScroll automatically, because the uiScroll takes items from the Datasource as is and never clones them. So you need to provide array of objects on Datasource.get (for copying by reference) and these objects should be passed to the Datasource from the outside where you can access and update them. I created simple demo, hope it helps: 

https://stackblitz.com/edit/angular-ngx-ui-scroll-1-1-0-beta

If not only item's data can change but item's view also can change, then we need to think how to force the uiScroll to take this into account. Currently (in v1.1.0-beta, which had been just released) the uiScroll has `Adapter.check` method (see [updated doc](https://github.com/dhilt/ngx-ui-scroll#adapter-api)) which can be useful for such case. When you know (or suspect) that some of items changed size, you may run `Adapter.check` and then the uiScroll will adjust it's internal params and fetch new items if needed.

**Comment by dhilt** [comment]
@Avishaidev 

**Remove**

This is important case and currently we have no mechanism to removing items via Adapter. We certainly want this feature. But for now it should be possible to do following workaround: 

 - set flag `removed` on each item which is false by default
 - item's template should depend on this flag (ngIf="!item.removed")
 - when you want to remove an item, you should turn `removed` to true and run `Adapter.check`

Technically item remains in the list but it becomes invisible.

**Comment by carthworks** [comment]
@Avishaidev   can you create a stackblitz demo for above explanation

**Comment by mxswat** [comment]
@Avishaidev I would like to remind you if you put a *ngIf on the same element of the directive you get the following error:
Can't have multiple template bindings on one element. Use only one attribute prefixed with *


Also if you try to use this trick with a list of 100000+ items and you "remove" all except the first the entire browser page freeze

**Comment by carthworks** [comment]
Hi @Avishaidev thanks for the respond.  Please check :[https://angular-ngx-ui-scroll-karthik.stackblitz.io](https://angular-ngx-ui-scroll-karthik.stackblitz.io).
My need is s_how two set of data on the same view port with_ button click (**search**, **normal**).  plz check , any help is appriciated

**Comment by carthworks** [comment]
sorry,  with code window - [https://stackblitz.com/edit/angular-ngx-ui-scroll-karthik?embed=1&file=src/app/app.component.html](https://stackblitz.com/edit/angular-ngx-ui-scroll-karthik?embed=1&file=src/app/app.component.html)

**Comment by mxswat** [comment]
Have you tried to use a filter?
Here's an example
https://stackoverflow.com/questions/34164413/how-to-apply-filters-to-ngfor

**Comment by dhilt** [comment]
The `Adapter.remove` method had been added to ngx-ui-scroll v1.1.0 which is now available via npm. The demo is here: https://dhilt.github.io/ngx-ui-scroll/#/adapter#remove. If there are any problems/questions, please feel free to create new GitHub issues.
