### ISSUE TITLE
What happens if Datasource gets an empty array? 

### ISSUE THREAD

**Issue by telion2** [dhilt/ngx-ui-scroll#94]
If I give uiScroll an empty array, the cpu usage of the browser suddenly skyrockets and the Dom 
is empty. 
Just do this to reproduce: 
```
datasourceInverted: IDatasource = {
    get: (index, count, success) => {
      const _index = -index - count + 1;
      console.log('index here is: ' + index + ' vs. ' + _index + ' : ' + count);
      const data = this.getData(_index, count).reverse();
      success(data);
    },
    settings: {
      startIndex: -10
    }
  };

  getData(index: number, count: number) {
    const data = [];
    const start = Math.max(1, index);
    const end = index + count - 1;
    console.log('Start: ' + start + ' end: ' + end + ' index: ' + index + ' count: ' + count);
    if (start <= end) {
      for (let i = start; i <= end; i++) {
        //data.push({id: i, text: 'item #' + i});
      }
    }
    return data;
  }
```
Why is this a problem? 
Because first: its quite common and easy to have empty arrays, especially if you have to get them from somewhere. 
Second: even if I later want to push data, the whole thing is stuck an therefore doesnt update. 

Also I have a general question: 
How do I properly update the data for uiScroll correctly, 
I figured that I call datasource.get to tell uiScroll to update but if I do that the data updates but the dom doesn't. 
So given a object[] of any size and changing elements on runtime, how do I update uiScroll?

**Comment by dhilt** [comment]
@telion2 Looks like you are dealing with [Inverted datasource](https://dhilt.github.io/ngx-ui-scroll/#/datasource#inverted-indexes) sample. I tried to comment out `data.push` locally and didn't see any performance issues. So speaking of CPU overload, memory leaks etc I would like to have more detailed repro, say, on stackblitz.

As you know, `Datasource.get` implementation must provide an array of `count` data-items started from `index` position. This is the only way we can update the uiScroll inner buffer and then the viewport. An empty result would be treated as reaching the edge of the dataset (eof/bof), and the uiScroll will place no further data requests. So, an empty array has to be passed if there are no items within given range `[index; index + count - 1]`, and it will prevent the uiScroll from further fetching in given direction. Passing empty result is a common practice for [Limited datasource](https://dhilt.github.io/ngx-ui-scroll/#/datasource#limited) implementations. 

It is a programmer responsibility to provide solid consistent data flow into the uiScroll using the Datasource API, which is the way to provide data updates to the uiScroll. Indexes must be uninterrupted from begin-of-file to end-of-file, empty result or result with length < `count` would mean eof/bof with no further updates. I would agree that the documentation might be updated to make this things more clear...

**Comment by dhilt** [comment]
Just updated [README](https://github.com/dhilt/ngx-ui-scroll#usage).

**Comment by telion2** [comment]
I finally found out why how it happens. 
So basically I'm using flexgrid of PrimeNg and this css class adds a padding of 0.5em. 
Consequently a scrollbar appears because of `overflow-y:auto `and if I use that scrollbar uiScroll goes mental if it doesnt have some data to display. 
Editor: 
https://stackblitz.com/edit/angular-hwtptc
Browser: 
https://angular-kw68xu.stackblitz.io 

About the updating: 
So the idea is to have message = [ el1, el2, ...]
provide .get() with a part of messages. If I update messages, am I supposed to run adapter.reload? 
so e.g.: 
```
get: (index, count, success) =>{
     ...
    for(let i = start; i < end; i++){
     data.push(message[i])
}
success(data); 
}

//somewhere else when updating messages: 
this.message = [newel1,newel2,...]
this.datasource.adapter.reload(someindex); 
```
If that is the case I have included the first adapter demo in the stackblitz showing an error with soem logger: 
```
ERROR TypeError: Cannot read property 'log' of undefined
    at Adapter.append (adapter.ts:218)
    at HelloComponent.ngOnInit (hello.component.ts:41)
    at checkAndUpdateDirectiveInline (provider.ts:212)
    at checkAndUpdateNodeInline (view.ts:429)
    at checkAndUpdateNode (view.ts:389)
    at debugCheckAndUpdateNode (services.ts:431)
    at debugCheckDirectivesFn (services.ts:392)
    at Object.eval [as updateDirectives] (AppComponent.html:1)
    at Object.debugUpdateDirectives [as updateDirectives] (services.ts:386)
    at checkAndUpdateView (view.ts:359)
```
Is that an error from my side? Should make a new issue for that?

**Comment by telion2** [comment]
That error also only appears in the console of the browser and not in the stackblitz console.

**Comment by dhilt** [comment]
@telion2 Having your demo I was able to investigate the error (Cannot read property 'log' of undefined) and created separate bug issue https://github.com/dhilt/ngx-ui-scroll/issues/96. It's definitely the UIScroll bug and I'll look into it.

Another one issue I see is that you may call `Adapter.append` during the UIScroll workflow is not stopped. For example, the UIScroll is going to fetch 1..5 items, then 6..11 and then -4..0. Append might fire in-between these fetches. So I would recommend to wait until the UIScroll is stopped:

```
    const adapter = this.AdapterDatasource.adapter;
    const sub = adapter.isLoading$.subscribe(isLoading => {
      if (!isLoading) {
        sub.unsubscribe();
        adapter.append({id:100, text:'new item' + 100}); 
        // adapter.reload(0); 
      }
    });
```

Also, I commented out `Adapter.reload` call because it leads to getting the result of `Adapter.append` lost (and you probably need to think [how to sync](https://dhilt.github.io/ngx-ui-scroll/#/adapter#items-count) UIScroll buffer and Datasource updates).

________

Then, if there is nothing to show, the UIScroll stops with no background processes that might use CPU. Playing with your demo I don't see any issues with empty results on the UIScroll side.

________

On items run-time updates. I would split updates onto two parts: array destructive (adding new items or removing old items) and array persistent (changing existed items content). For the first group we have `Adapter.remove`, `Adapter.append`, `Adapter.prepend`. For the second group we have no Adapter-based mechanism of updating buffered items run-time, only `Adapter.check` could be useful. The thing is that the UIScroll never duplicates incoming data, it deals with it as is. So if your datasource provides an array of objects, the reference to each item-object will be persistent across the UIScroll internal procedures. This means you may update you items out of UIScroll (look at [this demo](https://stackblitz.com/edit/angular-ngx-ui-scroll-1-1-0-beta). But if you expect the updated item might change its size, you may call `Adapter.check` which will check it, adjust scrollbar params and force new data fetch if needed. So basically, you might be able to make your updates without `Adapter.reload`.

**Comment by telion2** [comment]
Have run the Firefox Profiler on the stackblitz I provided. In the Stackblitz I intended to reproduce the CPU Overhead Issue with the CPUdatasource and the #96 with the AdapterDatasource. 
(You are right however that I didnt use the adapter.append etc. correctly) 

The CPUDatasource Beeing the first empty scroll viewport. If the the scrollbar doesnt appear then there is no issue, but if the padding is at 0.5em (or thats the padding I used) the scrollbar appears. 
The CPU will then rise if you try to scroll (down). 
Looking into the profiling result I can see that some timeout funktion takes forever and in the JS-Flamechart a setFirstIndexBuffer takes forever. 


Profiling Result: Import it into Firefox Runtime Analysis. 
[profile.zip](https://github.com/dhilt/ngx-ui-scroll/files/3524389/profile.zip)

Firefox has some "Website to slow, shall we stop it feature" which enabled me to profile it. I couldnt find it in Chrome, so I couldnt profile it in Chrome. 

Thanks for the hint with adaper.check btw.

**Comment by telion2** [comment]
It could be easily resolved by the user if the user removes the I think top-bot padding for vertical scrolling.

**Comment by dhilt** [comment]
@telion2 The repro is not obvious, but now I see it. Your last detalization was very helpful. In short. The scrollbar you forced to appear by padding allows a user to scroll a bit. Firing a scroll event runs the UIScroll workflow, which hangs during PreFetch process. This hanging is nothing but infinite loop, it's not a background process. I described it in a separate issue https://github.com/dhilt/ngx-ui-scroll/issues/98. It definitely must be fixed on the UIScroll end.

Thanks for your inputs!

**Comment by dhilt** [comment]
@telion2 ngx-ui-scroll v1.2.0 [has been released](https://github.com/dhilt/ngx-ui-scroll/releases/tag/v1.2.0), it is available via npm. It contains fixes for problems discussing here. If you have another problems/questions, please feel free to open new issues.

**Comment by telion2** [comment]
Props. I've checked it out aswell and it works. Now high Cpu usage and no Error in the console. 
For anyone who cares: https://stackblitz.com/edit/angular-xisrxn 
(It's no real test, I just fixed my repro with the new version of uiScroll)
